const Billing = require('../models/Billing');
const Usage = require('../models/Usage');
const User = require('../models/User');
const PLANS = require('../config/plans');
const { generateInvoicePDF } = require('../services/pdfService');
const { sendInvoiceEmail, sendPaymentReceiptEmail } = require('../utils/email');
const crypto = require('crypto');
const Razorpay = require('razorpay');

const razorpay = new Razorpay({
    key_id: process.env.RAZORPAY_KEY_ID,
    key_secret: process.env.RAZORPAY_KEY_SECRET,
});

const calculateBillingForPeriod = async (userId, period, plan) => {
    const startDate = new Date(period + '-01');
    const endDate = new Date(startDate.getFullYear(), startDate.getMonth() + 1, 1);
    const usage = await Usage.find({ userId, timestamp: { $gte: startDate, $lt: endDate } });

    const totalRequests = usage.length;
    const includedRequests = Math.min(totalRequests, plan.requestLimit);
    const overageRequests = Math.max(0, totalRequests - plan.requestLimit);
    const overageCost = parseFloat((overageRequests * plan.costPerRequest).toFixed(2));
    const planFee = plan.price;
    const totalCost = parseFloat((planFee + overageCost).toFixed(2));

    return { totalRequests, includedRequests, overageRequests, planFee, overageCost, totalCost };
};

const getBilling = async (req, res) => {
    try {
        const billing = await Billing.find({ userId: req.userId }).sort({ period: -1 });
        res.json(billing);
    } catch (error) {
        res.status(500).json({ message: 'Server error' });
    }
};

const getCurrentUsage = async (req, res) => {
    try {
        const now = new Date();
        const period = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;
        const user = await User.findById(req.userId);
        const plan = PLANS[user.plan] || PLANS.free;
        const calc = await calculateBillingForPeriod(req.userId, period, plan);

        res.json({
            period,
            plan: user.plan,
            planDetails: plan,
            ...calc,
            requestsRemaining: Math.max(0, plan.requestLimit - calc.totalRequests),
            usagePercent: Math.min(100, Math.round((calc.totalRequests / plan.requestLimit) * 100)),
        });
    } catch (error) {
        res.status(500).json({ message: 'Server error' });
    }
};

// Helper: create billing record + send invoice email with PDF
const createAndSendInvoice = async (userId, period, plan, user, isAutoGenerated = false) => {
    const calc = await calculateBillingForPeriod(userId, period, plan);

    // Due date: 15 days from invoice creation
    const dueDate = new Date();
    dueDate.setDate(dueDate.getDate() + 15);

    const billing = new Billing({
        userId,
        period,
        plan: user.plan,
        ...calc,
        isAutoGenerated,
        dueDate,
        isPaid: calc.totalCost === 0 && calc.totalRequests === 0,
    });
    await billing.save(); // triggers pre-save hook for invoice number

    // Send invoice email with PDF attachment (non-blocking)
    if (process.env.EMAIL_USER && process.env.EMAIL_PASS) {
        generateInvoicePDF(billing, user)
            .then(pdfBuffer => sendInvoiceEmail(user.email, user.username, billing, pdfBuffer))
            .catch(err => console.error('[email] Invoice email failed:', err.message));
    }

    return billing;
};

const generateBilling = async (req, res) => {
    try {
        const { period } = req.body;
        if (!period) return res.status(400).json({ message: 'Period is required (e.g. 2026-05)' });

        const now = new Date();
        const currentPeriod = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;
        if (period >= currentPeriod) {
            return res.status(400).json({
                message: `Cannot generate invoice for ${period} — the month hasn't ended yet. Invoices are auto-generated on the 1st of the following month.`
            });
        }

        const existing = await Billing.findOne({ userId: req.userId, period });
        if (existing) return res.status(400).json({ message: 'Invoice already exists for this period' });

        const user = await User.findById(req.userId);
        const plan = PLANS[user.plan] || PLANS.free;
        const billing = await createAndSendInvoice(req.userId, period, plan, user, false);

        res.status(201).json(billing);
    } catch (error) {
        console.error('[billing] generateBilling error:', error.message);
        res.status(500).json({ message: 'Server error' });
    }
};

// Download invoice PDF
const downloadInvoice = async (req, res) => {
    try {
        const billing = await Billing.findOne({ _id: req.params.id, userId: req.userId });
        if (!billing) return res.status(404).json({ message: 'Invoice not found' });

        const user = await User.findById(req.userId);
        const pdfBuffer = await generateInvoicePDF(billing, user);

        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename="${billing.invoiceNumber}.pdf"`);
        res.send(pdfBuffer);
    } catch (error) {
        console.error('[billing] PDF error:', error.message);
        res.status(500).json({ message: 'Error generating PDF' });
    }
};

const createPaymentOrder = async (req, res) => {
    try {
        const { billingId } = req.body;
        const billing = await Billing.findOne({ _id: billingId, userId: req.userId });
        if (!billing) return res.status(404).json({ message: 'Billing record not found' });
        if (billing.isPaid) return res.status(400).json({ message: 'Already paid' });

        const amountInPaise = Math.max(Math.round(billing.totalCost * 100), 100);
        const order = await razorpay.orders.create({
            amount: amountInPaise,
            currency: 'INR',
            receipt: billing.invoiceNumber || `billing_${billingId}`,
        });

        console.log(`[billing] Order created: ${order.id} for ${billing.invoiceNumber}`);
        res.json({ orderId: order.id, amount: order.amount, currency: order.currency });
    } catch (error) {
        console.error('[billing] Order error:', error.message);
        res.status(500).json({ message: error.error?.description || 'Error creating payment order' });
    }
};

const verifyPayment = async (req, res) => {
    try {
        const { orderId, paymentId, signature, billingId } = req.body;

        const hmac = crypto.createHmac('sha256', process.env.RAZORPAY_KEY_SECRET);
        hmac.update(`${orderId}|${paymentId}`);
        if (hmac.digest('hex') !== signature) {
            return res.status(400).json({ message: 'Payment signature mismatch' });
        }

        const billing = await Billing.findOneAndUpdate(
            { _id: billingId, userId: req.userId },
            { isPaid: true, paymentId, orderId, paidAt: new Date() },
            { new: true }
        );
        if (!billing) return res.status(404).json({ message: 'Billing record not found' });

        // Send payment receipt email (non-blocking)
        if (process.env.EMAIL_USER && process.env.EMAIL_PASS) {
            User.findById(req.userId).then(user => {
                if (user) sendPaymentReceiptEmail(user.email, user.username, billing)
                    .catch(err => console.error('[email] Receipt email failed:', err.message));
            });
        }

        res.json({ message: 'Payment verified successfully', billing });
    } catch (error) {
        res.status(500).json({ message: 'Error verifying payment' });
    }
};

module.exports = { getBilling, getCurrentUsage, generateBilling, downloadInvoice, createPaymentOrder, verifyPayment, createAndSendInvoice };
