const mongoose = require('mongoose');

// Auto-increment invoice number counter
const counterSchema = new mongoose.Schema({
    _id: { type: String, required: true },
    seq: { type: Number, default: 0 }
});
const Counter = mongoose.model('Counter', counterSchema);

const billingSchema = new mongoose.Schema({
    invoiceNumber: { type: String, unique: true },    // e.g. INV-2026-0001
    userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    period: { type: String, required: true },
    totalRequests: { type: Number, default: 0 },
    includedRequests: { type: Number, default: 0 },
    overageRequests: { type: Number, default: 0 },
    planFee: { type: Number, default: 0 },
    overageCost: { type: Number, default: 0 },
    totalCost: { type: Number, default: 0 },
    plan: { type: String, default: 'free' },
    isPaid: { type: Boolean, default: false },
    isAutoGenerated: { type: Boolean, default: false },
    paymentId: { type: String },
    orderId: { type: String },
    paidAt: { type: Date },
    dueDate: { type: Date },                          // payment due date
    overdueReminderSentAt: { type: [Date], default: [] }, // track reminder sends
    createdAt: { type: Date, default: Date.now }
});

billingSchema.index({ userId: 1, period: -1 });
billingSchema.index({ isPaid: 1, dueDate: 1 });       // for overdue queries

// Auto-generate invoice number before save
billingSchema.pre('save', async function (next) {
    if (this.invoiceNumber) return next();
    try {
        const year = new Date().getFullYear();
        const counter = await Counter.findByIdAndUpdate(
            `invoice_${year}`,
            { $inc: { seq: 1 } },
            { new: true, upsert: true }
        );
        this.invoiceNumber = `INV-${year}-${String(counter.seq).padStart(4, '0')}`;
        next();
    } catch (err) {
        next(err);
    }
});

module.exports = mongoose.model('Billing', billingSchema);
